services:
  db:
    image: postgres:14.3-alpine
    restart: always
    container_name: middleware-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mhqagent
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_prepared_transactions=0"]

  dbmate:
    image: public.ecr.aws/y4x5l0o7/dbmate-docker:latest
    container_name: middleware-dbmate
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mhqagent?sslmode=disable
    working_dir: /
    command: bash -c  "dbwait.sh && dbmate up && dbmate dump"

  scripts:
    image: public.ecr.aws/y4x5l0o7/mhq-sync-scripts:latest
    container_name: middleware-sync-agent
    restart: always
    depends_on:
      - db
      - dbmate
    links:
      - db
    volumes:
      - ./config.json:/root/config.json
    env_file:
      - .env
volumes:
  pgdata: {}
